export const PRODUCT_IDS = Object.freeze([
  "cmb-guangdong-business-loan",
  "pingan-orange-tax-loan",
  "pingan-foreign-trade-logistics-loan",
  "webank-cross-border-data-loan",
  "linklogis-amazon-sc",
  "linklogis-amazon-vc",
  "linklogis-b2b-factoring",
]);

const deepFreeze = (value) => {
  if (value === null || typeof value !== "object") return value;
  for (const nestedValue of Object.values(value)) deepFreeze(nestedValue);
  return Object.freeze(value);
};

const product = (definition) => Object.freeze({
  enabled: true,
  effectiveDate: "2026-08-21",
  fitWeights: Object.freeze({
    businessModel: 30,
    scaleAndLimit: 20,
    cashFlow: 15,
    currencyTermUse: 15,
    controlAcceptance: 10,
    documentation: 10,
  }),
  missingDataPolicy: "review",
  ...definition,
  ruleSet: Object.freeze(definition.ruleSet.map((rule) => Object.freeze({
    ...rule,
    value: deepFreeze(rule.value),
  }))),
});

const source = (section) => `2026-08-21 AI 产品匹配设计，第 ${section} 节`;

export const PRODUCT_CATALOG = Object.freeze([
  product({
    id: "cmb-guangdong-business-loan",
    institution: "招商银行",
    name: "招商银行经营贷",
    currency: "RMB",
    geographicFocus: Object.freeze(["深圳", "佛山", "东莞", "惠州"]),
    pricing: Object.freeze({ annualizedRate: null, note: "资料未提供基础系数和附加系数具体取值。" }),
    term: Object.freeze({ maximumMonths: null }),
    limit: Object.freeze({ minimum: null, maximum: null, currency: "RMB", note: "第一期只判断准入和额度边界。" }),
    version: "2026-08-21",
    source: source("7.1"),
    amountEstimator: Object.freeze({
      type: "eligibilityOnly",
      formula: null,
      preciseAmountAvailable: false,
      note: "第一期只判断准入和额度边界，不生成精确额度。",
      followUp: "需客户经理补充系数。",
    }),
    ruleSet: [
      { id: "registered-in-guangdong", field: "registeredProvince", operator: "equals", value: "广东省", severity: "hard", message: "企业注册地需在广东省内。" },
      { id: "settlement-account-opened-one-year", field: "settlementAccountOpenedMonths", operator: "minInclusive", value: 12, severity: "hard", message: "结算账户开户需满 1 年。" },
      { id: "settlement-account-flow-normal", field: "settlementAccountFlowNormal", operator: "truthy", value: true, severity: "hard", message: "结算账户流水需无异常。" },
      { id: "company-age-and-rating", field: "companyOperatingYears", operator: "custom", value: { anyOf: [{ minimumYears: 5 }, { minimumYears: 3, minimumRating: "5C+" }] }, severity: "hard", message: "企业成立需满 5 年，或成立满 3 年且评级达到 5C+。" },
      { id: "annual-revenue-minimum", field: "annualRevenueRmb", operator: "minInclusive", value: 10000000, severity: "hard", message: "年营收需不低于 1000 万元。" },
      { id: "asset-liability-ratio-below-80", field: "assetLiabilityRatio", operator: "custom", value: { comparison: "below", threshold: 0.8 }, severity: "hard", message: "资产负债率需低于 80%。" },
      { id: "internal-rating-minimum", field: "internalBankRating", operator: "minInclusive", value: "6A", severity: "hard", message: "行内评级需不低于 6A。" },
      { id: "credit-bank-count-maximum", field: "creditBankCount", operator: "maxInclusive", value: 4, severity: "hard", message: "授信银行不超过 4 家。" },
      { id: "credit-exposure-within-net-assets", field: "creditExposureToNetAssets", operator: "maxInclusive", value: 1, severity: "hard", message: "授信敞口不超过净资产。" },
      { id: "no-risk-warning", field: "hasRiskWarning", operator: "falsy", value: false, severity: "hard", message: "请补充并核验企业风险状态。", internalReason: "预警信息" },
      { id: "no-aml-blacklist", field: "isOnAmlBlacklist", operator: "falsy", value: false, severity: "hard", message: "请完成企业合规状态核验。", internalReason: "反洗钱黑名单" },
      { id: "no-overdue-principal-or-interest", field: "hasOverduePrincipalOrInterest", operator: "falsy", value: false, severity: "hard", message: "请补充并核验企业还款状态。", internalReason: "逾期欠息" },
      { id: "no-adverse-credit-status", field: "hasAdverseCreditStatus", operator: "falsy", value: false, severity: "hard", message: "请补充并核验企业信用状态。", internalReason: "不良关注类信用状态" },
      { id: "no-dishonesty-record", field: "hasDishonestyRecord", operator: "falsy", value: false, severity: "hard", message: "请完成企业公开信息核验。", internalReason: "失信名单" },
      { id: "continuous-financial-statements", field: "financialStatementsContinuous", operator: "truthy", value: true, severity: "hard", message: "财务报表需连续。" },
      { id: "controller-status-normal", field: "controllerStatusNormal", operator: "truthy", value: true, severity: "hard", message: "实控人状态需正常。" },
      { id: "non-sensitive-industry", field: "industry", operator: "custom", value: { disallowed: ["资本运作", "中介劳务", "大宗贵金属", "高风险领域"] }, severity: "review", message: "请提供行业经营信息，以便人工复核。", internalReason: "资本运作、中介劳务、大宗贵金属和高风险领域" },
    ],
  }),
  product({
    id: "pingan-orange-tax-loan",
    institution: "平安银行",
    name: "平安银行橙业贷税金方案",
    currency: "RMB",
    pricing: Object.freeze({ annualizedRate: Object.freeze({ minimum: "3.5%", maximum: "8%" }), basis: "风险分层定价" }),
    term: Object.freeze({ creditMaximumMonths: 36, drawMaximumMonths: 12, revolving: true }),
    limit: Object.freeze({ minimum: 50000, maximum: 3000000, currency: "RMB", revolving: true }),
    version: "2026-08-21",
    source: source("7.2"),
    amountEstimator: Object.freeze({
      type: "rangeOnly",
      formula: null,
      preciseAmountAvailable: false,
      note: "资料未提供税金到额度的精确核额公式。",
      followUp: "根据资料授权完整度提示下一步。",
    }),
    ruleSet: [
      { id: "eligible-applicant-role", field: "applicantRole", operator: "oneOf", value: ["法人", "第一大自然人股东", "个体工商户负责人"], severity: "hard", message: "申请人需为法人、第一大自然人股东或个体工商户负责人。" },
      { id: "company-registration-two-years", field: "companyRegisteredMonths", operator: "minInclusive", value: 24, severity: "hard", message: "企业注册需满 24 个月。" },
      { id: "applicant-age-minimum", field: "applicantAge", operator: "minInclusive", value: 25, severity: "hard", message: "申请人年龄需满 25 岁。" },
      { id: "applicant-age-maximum", field: "applicantAge", operator: "maxInclusive", value: 65, severity: "hard", message: "申请人年龄不超过 65 岁。" },
      { id: "additional-authorizations-over-500k", field: "requestedAmountRmb", operator: "custom", value: { whenAtLeast: 500000, requiresAllTruthy: ["spouseCreditAuthorization", "controllerCreditAuthorization", "applicableGuarantee"] }, severity: "hard", message: "申请 50 万元及以上时，请补充相关授权及担保资料。" },
    ],
  }),
  product({
    id: "pingan-foreign-trade-logistics-loan",
    institution: "平安银行",
    name: "平安银行外贸物流贷",
    currency: "RMB",
    pricing: Object.freeze({ annualizedRate: null }),
    term: Object.freeze({ maximumMonths: null }),
    limit: Object.freeze({ maximum: 5000000, currency: "RMB" }),
    version: "2026-08-21",
    source: source("7.3"),
    amountEstimator: Object.freeze({
      type: "formulaWithCap",
      formula: "annualSales × industryCoefficient，与税票核额综合判断",
      industryCoefficients: Object.freeze({ 批发零售: "10%", 加工制造: "16%" }),
      maximum: 5000000,
      currency: "RMB",
      note: "超过 300 万元还需满足税票质量或进出口占比条件，以及连续经营满 5 年。",
    }),
    ruleSet: [
      { id: "domestic-sme-legal-entity", field: "entityType", operator: "equals", value: "境内注册中小微法人企业", severity: "hard", message: "申请主体需为境内注册中小微法人企业。" },
      { id: "eligible-industry", field: "industry", operator: "oneOf", value: ["批发零售", "加工制造"], severity: "hard", message: "行业需为批发零售或加工制造。" },
      { id: "company-operating-two-years", field: "companyOperatingYears", operator: "minInclusive", value: 2, severity: "hard", message: "企业经营需满 2 年。" },
      { id: "controller-industry-experience", field: "controllerIndustryExperienceYears", operator: "minInclusive", value: 5, severity: "hard", message: "实控人从业经历需不少于 5 年。" },
      { id: "self-operated-import-export", field: "selfOperatedImportExport", operator: "truthy", value: true, severity: "hard", message: "企业需从事自营进出口。" },
      { id: "import-export-license", field: "hasImportExportLicense", operator: "truthy", value: true, severity: "hard", message: "企业需拥有进出口经营权。" },
      { id: "foreign-exchange-class-a", field: "foreignExchangeClassification", operator: "equals", value: "A类", severity: "hard", message: "外汇管理分类需为 A 类。" },
      { id: "customs-credit-not-dishonest", field: "customsCreditClassification", operator: "custom", value: { disallowed: ["失信类"] }, severity: "hard", message: "请完成海关信用分类核验。", internalReason: "海关信用为失信类" },
      { id: "import-export-volume-last-12-months", field: "importExportAmountLast12MonthsUsd", operator: "minInclusive", value: 500000, severity: "hard", message: "近 12 个月进出口额需不低于 50 万美元。" },
      { id: "import-export-volume-13-to-24-months", field: "importExportAmountMonths13To24Usd", operator: "minInclusive", value: 500000, severity: "hard", message: "13-24 个月进出口额需不低于 50 万美元。" },
      { id: "recent-import-export-record", field: "monthsSinceLatestImportExport", operator: "maxInclusive", value: 3, severity: "hard", message: "最近进出口记录需在 3 个月内。" },
      { id: "import-export-frequency", field: "importExportCountLast12Months", operator: "minInclusive", value: 2, severity: "hard", message: "近 12 个月进出口记录需不少于 2 次。" },
      { id: "import-export-revenue-share", field: "importExportRevenueShare", operator: "minInclusive", value: 0.5, severity: "hard", message: "进出口业务占营收需不低于 50%。" },
      { id: "commodity-share", field: "commodityRevenueShare", operator: "maxInclusive", value: 0.2, severity: "review", message: "大宗商品占比原则上不超过 20%。" },
      { id: "sales-decline-review", field: "twoYearSalesDecline", operator: "custom", value: { above: 0.3, outcome: "review" }, severity: "review", message: "请提供两个年度的销售收入，以便人工复核。", internalReason: "两个年度销售收入下滑超过 30%" },
      { id: "debt-ratio-by-industry-and-tax-basis", field: "debtRatio", operator: "custom", value: { nonTaxInvoice: { 加工制造: 0.65, 批发零售: 0.5 }, taxInvoice: { 加工制造: 0.7, 批发零售: 0.55 } }, severity: "hard", message: "负债比需符合所属行业及税票口径要求。" },
      { id: "additional-conditions-over-3m", field: "requestedAmountRmb", operator: "custom", value: { whenAbove: 3000000, requires: { anyOf: ["taxInvoiceQuality", "importExportRevenueShare"], companyOperatingYears: { minInclusive: 5 } } }, severity: "hard", message: "额度超过 300 万元时，需满足税票质量或进出口占比条件，并连续经营满 5 年。" },
      { id: "core-asset-liability-over-3m", field: "requestedAmountRmb", operator: "custom", value: { when: { anyOf: [{ nonTaxInvoice: true }, { amountAbove: 3000000 }] }, requires: { coreAssetLiabilityRatioMaximum: 0.8 } }, severity: "review", message: "非税票或额度超过 300 万元时，核心资产负债率原则上不超过 80%。" },
    ],
  }),
  product({
    id: "webank-cross-border-data-loan",
    institution: "微众银行",
    name: "微众银行跨境电商数据贷",
    currency: "RMB",
    pricing: Object.freeze({ annualizedRate: null }),
    term: Object.freeze({ maximumMonths: null }),
    limit: Object.freeze({ maximum: 20000000, currency: "RMB" }),
    version: "2026-08-21",
    source: source("7.4"),
    amountEstimator: Object.freeze({
      type: "referenceRange",
      formula: "近 12 个月月均回款 × 1 至 3.5",
      multipleRange: Object.freeze({ minimum: 1, maximum: 3.5, mainstreamMinimum: 2, mainstreamMaximum: 2.5 }),
      maximum: 20000000,
      currency: "RMB",
      note: "精确倍数由综合评级决定，网站只展示参考范围。",
    }),
    ruleSet: [
      { id: "amazon-collection-entity", field: "collectionPlatform", operator: "equals", value: "Amazon", severity: "hard", message: "需为 Amazon 店铺收款主体。" },
      { id: "domestic-registration", field: "registeredInChina", operator: "truthy", value: true, severity: "hard", message: "企业需在境内注册。" },
      { id: "currently-operating-six-months", field: "currentOperatingMonths", operator: "minInclusive", value: 6, severity: "hard", message: "企业当前在营需满 6 个月。" },
      { id: "legal-representative-age-minimum", field: "legalRepresentativeAge", operator: "minInclusive", value: 23, severity: "hard", message: "法人年龄需满 23 岁。" },
      { id: "legal-representative-age-maximum", field: "legalRepresentativeAge", operator: "maxInclusive", value: 65, severity: "hard", message: "法人年龄不超过 65 岁。" },
      { id: "no-current-overdue", field: "hasCurrentOverdue", operator: "falsy", value: false, severity: "hard", message: "请补充并核验企业及个人还款状态。", internalReason: "当前逾期" },
      { id: "no-material-credit-or-judicial-issues", field: "hasMaterialCreditOrJudicialIssue", operator: "falsy", value: false, severity: "hard", message: "请补充并核验企业及个人信用与司法信息。", internalReason: "资料列明的重大征信、司法负面" },
      { id: "one-store-operating-one-year", field: "longestStoreOperatingMonths", operator: "minInclusive", value: 12, severity: "hard", message: "至少一家店铺经营需满 1 年。" },
      { id: "single-store-first-order-two-years", field: "storeCount", operator: "custom", value: { whenEquals: 1, requires: { firstOrderMonthsAgo: { minExclusive: 24 } } }, severity: "hard", message: "仅有一家店铺时，第一笔订单距今需超过 2 年。" },
      { id: "sales-last-12-months", field: "allStoreSalesLast12MonthsRmb", operator: "minInclusive", value: 2000000, severity: "hard", message: "所有店铺近 12 个月销售额需不低于 200 万元。" },
      { id: "repayments-last-12-months", field: "allStoreRepaymentsLast12MonthsRmb", operator: "minInclusive", value: 500000, severity: "hard", message: "所有店铺近 12 个月回款额需不低于 50 万元。" },
      { id: "refund-rate-last-three-months", field: "refundRateLast3Months", operator: "maxInclusive", value: 0.4, severity: "hard", message: "近 3 个月退款率不高于 40%。" },
      { id: "participating-store-operating-days", field: "participatingStoreOperatingDays", operator: "minInclusive", value: 180, severity: "hard", message: "参与核额店铺经营需不少于 180 天。" },
      { id: "participating-store-normal", field: "participatingStoreStatus", operator: "equals", value: "正常", severity: "hard", message: "参与核额店铺账户状态需正常。" },
      { id: "participating-store-ahr", field: "participatingStoreAhr", operator: "minExclusive", value: 200, severity: "hard", message: "参与核额店铺 AHR 需高于 200。" },
      { id: "amazon-us-only", field: "marketplace", operator: "equals", value: "Amazon 美国站", severity: "hard", message: "第一期只准入 Amazon 美国站。" },
      { id: "fba-inventory-turnover", field: "fbaInventoryTurnoverCount", operator: "minExclusive", value: 2, severity: "hard", message: "FBA 库存周转次数需大于 2。" },
      { id: "borrower-matches-collection-entity", field: "borrowerMatchesCollectionEntity", operator: "truthy", value: true, severity: "hard", message: "借款主体需与收款主体一致。" },
      { id: "participating-store-locked", field: "participatingStoreLocked", operator: "truthy", value: true, severity: "hard", message: "参与核额店铺需按要求锁定。" },
    ],
  }),
  product({
    id: "linklogis-amazon-sc",
    institution: "联易融",
    name: "联易融 Amazon SC 卖家融资贷",
    currency: "USD",
    pricing: Object.freeze({ annualizedRate: Object.freeze({ minimum: "9%", maximum: "11%" }) }),
    term: Object.freeze({ financingDays: 90, repayment: "随借随还", revolving: true }),
    limit: Object.freeze({ maximumPerStore: 3000000, currency: "USD", revolving: true }),
    version: "2026-08-21",
    source: source("7.5"),
    amountEstimator: Object.freeze({ type: "manualAssessment", formula: null, note: "单店最高 300 万美元，可循环。" }),
    ruleSet: [
      { id: "eligible-company-location", field: "companyLocation", operator: "oneOf", value: ["大陆", "境外"], severity: "hard", message: "申请主体需为大陆或境外公司。" },
      { id: "amazon-store", field: "platform", operator: "equals", value: "Amazon", severity: "hard", message: "需为 Amazon 店铺。" },
      { id: "single-store-annual-gmv", field: "singleAmazonStoreAnnualGmvUsd", operator: "minExclusive", value: 5000000, severity: "hard", message: "Amazon 单店铺年 GMV 需大于 500 万美元。" },
      { id: "amazon-trading-history", field: "amazonTradingHistoryMonths", operator: "minExclusive", value: 12, severity: "hard", message: "与 Amazon 交易历史需超过 12 个月。" },
      { id: "collection-account-switch", field: "collectionAccountArrangement", operator: "custom", value: { anyOf: ["接受切换至合作支付公司或银行", "已合作账户"] }, severity: "hard", message: "需接受将回款账户切换至合作支付公司或银行；已合作账户可免切换。" },
    ],
  }),
  product({
    id: "linklogis-amazon-vc",
    institution: "联易融",
    name: "联易融 Amazon VC 发货后融资贷",
    currency: "USD",
    pricing: Object.freeze({ annualizedRate: Object.freeze({ minimum: "8%", maximum: "10%" }) }),
    term: Object.freeze({ maximumDays: 120, revolving: true }),
    limit: Object.freeze({ maximum: null, currency: "USD", revolving: true, note: "额度不设固定上限。" }),
    version: "2026-08-21",
    source: source("7.6"),
    amountEstimator: Object.freeze({ type: "receivablesAssessment", formula: null, note: "额度不设固定上限。" }),
    ruleSet: [
      { id: "eligible-company-location", field: "companyLocation", operator: "oneOf", value: ["大陆", "香港", "美国"], severity: "hard", message: "申请主体需为 Amazon VC 的大陆、香港或美国主体。" },
      { id: "amazon-vc-entity", field: "amazonProgram", operator: "equals", value: "Amazon VC", severity: "hard", message: "申请主体需为 Amazon VC 主体。" },
      { id: "amazon-vc-us-site", field: "marketplace", operator: "equals", value: "美国", severity: "hard", message: "经营站点需为美国。" },
      { id: "amazon-annual-gmv", field: "amazonAnnualGmvUsd", operator: "minExclusive", value: 2000000, severity: "hard", message: "Amazon 年 GMV 需大于 200 万美元。" },
      { id: "amazon-trading-history", field: "amazonTradingHistoryMonths", operator: "minExclusive", value: 6, severity: "hard", message: "与 Amazon 交易历史需超过 6 个月。" },
      { id: "noa-and-collection-account-switch", field: "acceptsNoaAndCollectionAccountSwitch", operator: "truthy", value: true, severity: "hard", message: "需接受发送 NOA 和回款账户切换。" },
    ],
  }),
  product({
    id: "linklogis-b2b-factoring",
    institution: "联易融",
    name: "联易融 B2B 保理融资",
    currency: "USD",
    pricing: Object.freeze({ annualizedRate: Object.freeze({ minimum: "8%", maximum: "12%" }) }),
    term: Object.freeze({ maximumDays: 120 }),
    limit: Object.freeze({ maximum: null, currency: "USD", note: "额度按交易应收数据评估，无固定上限。" }),
    version: "2026-08-21",
    source: source("7.7"),
    amountEstimator: Object.freeze({ type: "receivablesAssessment", formula: "按交易应收数据评估", note: "无固定上限。" }),
    ruleSet: [
      { id: "eligible-company-location", field: "companyLocation", operator: "oneOf", value: ["大陆", "境外"], severity: "hard", message: "申请主体需为大陆或境外公司。" },
      { id: "buyer-trading-history", field: "buyerTradingHistoryMonths", operator: "minExclusive", value: 12, severity: "hard", message: "与买方交易历史需超过 12 个月。" },
      { id: "annual-trading-volume", field: "annualTradingVolumeUsd", operator: "minExclusive", value: 2400000, severity: "hard", message: "年交易额需大于 240 万美元。" },
      { id: "eligible-buyer", field: "buyerEligibility", operator: "custom", value: { anyOf: ["准入 1P 商超", "已列明准入国家"] }, severity: "hard", message: "买方需属于准入 1P 商超或位于已列明准入国家。" },
      { id: "collection-account-switch", field: "acceptsCollectionAccountSwitch", operator: "truthy", value: true, severity: "hard", message: "需接受回款账户切换。" },
    ],
  }),
]);

export function getProductById(id) {
  return PRODUCT_CATALOG.find((productDefinition) => productDefinition.id === id);
}
