import { mountPromotionAdmin } from "./adminClient.mjs";

export function buildPromotionAdminPage() {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>销售推广 · 美鸥云贷</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fb;color:#182840;font:14px/1.6 system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif}
button,input,textarea{font:inherit}button,a,input,textarea{outline-offset:3px}button{cursor:pointer;border:1px solid #d9e2ee;border-radius:8px;background:#fff;padding:9px 14px;color:#31455f;font-weight:600}
button:hover{background:#edf4ff;border-color:#9abce9}button:disabled{opacity:.5;cursor:not-allowed}a{color:#245fd0;text-decoration:none}
.top{background:#fff;border-bottom:1px solid #e1e8f1}.nav{max-width:1360px;margin:auto;padding:19px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-size:18px;font-weight:800;color:#173463}.brand span{color:#2b6fe6;margin-right:10px}
main{max-width:1360px;margin:auto;padding:32px 28px 56px}.heading{display:flex;justify-content:space-between;align-items:start;gap:20px;margin-bottom:24px}.eyebrow{font-size:11px;font-weight:800;color:#3473d4;letter-spacing:2px}h1{font-size:30px;letter-spacing:-1px;margin:6px 0}h2{font-size:17px;margin:0 0 16px}p{margin:0;color:#65748b}.tag{background:#e6eefb;color:#3561a5;padding:5px 12px;border-radius:20px;white-space:nowrap}
.card{background:#fff;border:1px solid #e0e7f0;border-radius:14px;box-shadow:0 4px 18px #17346304}.auth{padding:20px;display:flex;align-items:end;gap:14px;flex-wrap:wrap;margin-bottom:20px}
label{display:grid;gap:6px;color:#506079;font-size:12px;font-weight:600}input,textarea{border:1px solid #d6e0ed;border-radius:8px;background:#fff;padding:10px 12px;color:#182840;min-width:0;width:100%}input:focus,textarea:focus{border-color:#367be5}textarea{resize:vertical;min-height:90px}
.auth label{flex:1;min-width:150px}.primary{background:#2468da;color:white;border-color:#2468da}.primary:hover{background:#1c56b7;color:#fff}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:22px}.stat{padding:20px 24px}.stat span{color:#66768d;font-size:12px}.stat strong{display:block;font-size:30px;margin:3px 0}.stat small{color:#8793a5}
.layout{display:grid;grid-template-columns:280px minmax(0,1fr);gap:20px}.editor{padding:24px;align-self:start}.editor label{margin-bottom:16px}.editor button{width:100%;margin-top:5px}.editor .hint{font-size:12px;margin:14px 0}.editor-status{font-size:12px;color:#225cb7;min-height:24px;margin-top:12px}
.list-head{padding:22px 24px 18px;border-bottom:1px solid #e7edf5}.filters{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.filters label{flex:1;min-width:130px}.filters button{white-space:nowrap}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:840px}th,td{text-align:left;padding:16px 18px;border-bottom:1px solid #edf1f7;vertical-align:middle}th{font-size:11px;color:#7b8799;font-weight:600;background:#fafbfd;white-space:nowrap}td{font-size:13px}td strong,td small{display:block}td small{font-size:11px;color:#8390a4;max-width:160px;overflow-wrap:anywhere}
.badge{background:#e5f5ed;color:#23885a;border-radius:20px;padding:4px 9px;font-size:11px;white-space:nowrap}.badge.paused{background:#eff1f5;color:#7b8799}.row-actions{white-space:nowrap}.row-actions button{padding:5px 7px;font-size:11px;border-color:transparent;color:#3065b7}
.empty{text-align:center;padding:55px 20px}.empty strong{display:block;font-size:16px;margin-bottom:8px}.foot{padding:16px 24px;font-size:12px;color:#6d7d94}.notice{padding:12px 16px;background:#fff4df;color:#926421;border-radius:8px;margin-bottom:16px}
.copy-area{padding:16px;margin-top:18px}.qr-panel{padding:24px;margin-top:20px;display:grid;grid-template-columns:180px 1fr;align-items:center;gap:24px}.qr-panel img{width:180px;max-width:100%;border:1px solid #e7edf5;border-radius:10px}.qr-panel h2{margin-bottom:8px}.qr-panel p{font-size:12px;margin-bottom:8px;overflow-wrap:anywhere}.download{display:inline-block;background:#2468da;color:white;padding:9px 18px;border-radius:8px;margin:8px 12px 0 0}
[hidden]{display:none!important}@media(max-width:1000px){.layout{grid-template-columns:1fr}.editor form{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.editor textarea{min-height:46px}.editor .hint{grid-column:1/-1}}@media(max-width:600px){main{padding:22px 16px}.nav{padding:16px}.heading .tag{display:none}h1{font-size:25px}.stats{gap:8px}.stat{padding:14px 12px}.stat strong{font-size:24px}.stat small{font-size:10px}.editor form{display:block}.auth{padding:16px}.auth button{width:100%}.qr-panel{grid-template-columns:1fr}.qr-panel img{margin:auto}.list-head{padding:18px 16px}}
</style></head><body>
<header class="top"><div class="nav"><a class="brand" href="/"><span>M</span>美鸥云贷 <small>· 管理中心</small></a><a href="/admin">客户管理 →</a></div></header>
<main>
<div class="heading"><div><div class="eyebrow">SALES PROMOTION</div><h1>让每一次推广，都有来源</h1><p>管理销售专属二维码，了解各销售带来的匿名访问情况。</p></div><span class="tag">销售推广 · 第一版</span></div>
<section class="card auth" aria-label="管理员认证"><label>管理员账户<input id="username" autocomplete="username" placeholder="输入管理员账户"></label><label>管理员密码<input id="password" type="password" autocomplete="current-password" placeholder="输入管理员密码"></label><button id="load" class="primary" type="button">读取 / 刷新数据</button></section>
<div id="configuration" class="notice" role="alert" hidden></div>
<section class="stats" aria-label="推广概览"><div class="card stat"><span>销售总数</span><strong id="sales-count">—</strong><small>包含已停用销售</small></div><div class="card stat"><span>所选日期访问次数</span><strong id="period-count">—</strong><small>未选日期时统计全部</small></div><div class="card stat"><span>累计推广访问次数</span><strong id="total-count">—</strong><small>访问次数 ≠ 客户人数</small></div></section>
<div class="layout"><aside class="card editor"><h2 id="editor-title">添加销售</h2><form id="sales-form"><label>销售姓名<input id="sales-name" required maxlength="80" placeholder="例如：张经理"></label><label>内部备注（选填）<textarea id="sales-note" maxlength="500" placeholder="例如：华南区域销售"></textarea></label><p class="hint">保存后自动生成专属推广码。销售姓名和备注仅在后台展示。</p><button id="save-sale" class="primary" type="submit">添加并生成推广码</button><button id="cancel-edit" type="button" hidden>取消编辑</button></form><div id="editor-status" class="editor-status" role="status"></div></aside>
<section class="card"><div class="list-head"><h2>销售推广明细</h2><div class="filters"><label>开始日期<input id="dateFrom" type="date"></label><label>结束日期<input id="dateTo" type="date"></label><button type="button" onclick="document.getElementById('load').click()">筛选</button><button id="clear-dates" type="button">全部日期</button></div></div>
<div class="table-wrap"><table><thead><tr><th>销售 / 备注</th><th>状态</th><th>所选日期访问</th><th>累计访问</th><th>最近访问 · 北京时间</th><th>推广操作</th></tr></thead><tbody id="sales-body"></tbody></table></div>
<div id="empty" class="empty"><strong>准备好第一张专属二维码</strong><p>登录后添加销售，即可复制链接和下载二维码。</p></div>
<div id="status" class="foot" role="status" aria-live="polite">请输入管理员账户和密码读取数据。</div></section></div>
<div id="copy-area" class="card copy-area" hidden><label>推广链接<input id="copy-link" readonly aria-label="可复制的推广链接"></label></div>
<section id="qr-panel" class="card qr-panel" hidden><img id="qr-image" alt="销售专属推广二维码"><div><h2 id="qr-title"></h2><p id="qr-state"></p><p id="qr-link"></p><a id="download-qr" class="download">下载 PNG 二维码</a><button id="close-qr" type="button">关闭</button></div></section>
<p style="margin-top:22px;font-size:12px">统计说明：二维码转发后的访问仍归于原销售。未填写资料的访问者为匿名，系统不会自动获得姓名、手机号或微信身份。</p>
</main><script>(${mountPromotionAdmin.toString()})(document, window);</script></body></html>`;
}
