import { salesLayout } from './layout.mjs';
import { mountAccountClient } from './accountClient.mjs';
export function buildAccountPage() {
  return salesLayout('账号与客户分配', `<div class="eyebrow">TEAM MANAGEMENT</div><h1>账号与客户分配</h1><p class="muted">为销售开通独立账号，分配客户并保留原始推广来源。</p>
  <section class="card"><h2>管理员认证</h2><div class="row"><label>管理员账户<input id="username" autocomplete="username"></label><label>管理员密码<input id="password" type="password" autocomplete="current-password"></label><button id="load" class="primary" type="button">读取 / 刷新</button></div></section>
  <section class="card"><h2>开通销售账号</h2><p class="muted">先在销售推广页添加销售，再在这里关联账号。设置密码后即可登录，无需首次改密。</p><form id="create-account" class="row"><label>关联销售<select id="sale-select"><option value="">请先读取数据</option></select></label><label>销售账户名<input id="account-name" autocomplete="off" required pattern="[a-zA-Z0-9._-]{3,64}"></label><label>初始密码<input id="initial-password" type="password" autocomplete="new-password" minlength="8" maxlength="128" required></label><button id="create-button" class="primary">创建账号</button></form>
  <div class="table-wrap"><table><thead><tr><th>销售</th><th>账户名</th><th>状态</th><th>操作</th></tr></thead><tbody id="account-rows"></tbody></table></div></section>
  <form id="reset-panel" class="card" hidden><h2 id="reset-title">重置密码</h2><p>重置会撤销该账户的全部登录，新密码需要由管理员安全交给销售。</p><div class="row"><label>新的初始密码<input id="reset-password" type="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><button id="reset-button" class="primary">确认重置</button><button id="reset-cancel" type="button">取消</button></div></form>
  <section class="card"><h2>客户分配</h2><div class="row"><label>负责销售<select id="owner-filter"><option value="">全部客户</option><option value="unassigned">待分配</option></select></label><label>查找客户<input id="customer-query" type="search" placeholder="企业、联系人或电话"></label><button id="filter" type="button">筛选</button></div><p class="muted">转交只改变当前负责人，原始来源保持不变。销售仅能查看当前负责的客户。</p><div class="table-wrap"><table><thead><tr><th>客户</th><th>联系方式</th><th>来源销售</th><th>当前负责</th><th>分配 / 转交</th></tr></thead><tbody id="customer-rows"></tbody></table></div></section>`, mountAccountClient);
}
